package com.backend.models.enums;

public enum MessageLink {
    BAD_REQUEST,
    NOT_FOUND,
    NAME_TAKEN,
    NAME_INCORRECT,
    EMAIL_TAKEN,
    EMAIL_INCORRECT,
    WRONG_LOGIN_NAME,
    WRONG_LOGIN_EMAIL,
    WRONG_LOGIN_PASSWORD,
    PERMISSION_NOT_ALLOWED,
    NAME_CHANGE_FORBIDDEN,
    EMAIL_CHANGE_FORBIDDEN,
    ALREADY_EXISTS,
    INTERNAL_ERROR,
    UNKNOWN_ERROR,
    PASSWORD_TOO_WEAK,
    TOKEN_EXPIRED,
    FIELD_REQUIRED,
    DATA_CONFLICT,
    OPERATION_FAILED,
    ITEM_NOT_FOUND,
}

